### ISSUE TITLE
Page not found for preparing apps for Production

### ISSUE THREAD

**Issue by sanket-thotange** [tolgee/documentation#360]
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/75122630/220267655-eac51370-d059-4951-8a1d-24da4a67bbf6.png">

**Comment by JanCizmar** [comment]
Where have you found the link?

**Comment by sanket-thotange** [comment]
I am using self hosted server and using Angular Integrate options.
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/75122630/220285581-175314a2-ddb7-4cc3-b62c-c5d4254b65fd.png">

**Comment by Webrow** [comment]
Updated to most recent, still a thing (it is not important for me at all, just a ping)

**Comment by JanCizmar** [comment]
Fixed here: https://github.com/tolgee/tolgee-platform/pull/1766
