### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by stepan662** [tolgee/documentation#649]
Some links on https://tolgee.io/js-sdk are not working (e.g. `language detection`, `formatting`, `in-context translating`). Seems weird, docosaurus should be catching this on build.

**Comment by harshil1712** [comment]
Hey @stepan662, I checked it and I do not get a 404 for any of the links. When opening the site in incognito, I got a 404 on the first render. However, that didn't happen again. I couldn't reproduce the issue. My guess is, the links are correct. The server is not able to serve them correctly on first request. We need to dig this deeper.

**Comment by JanCizmar** [comment]
I checked the mentioned links and it works fine for me 🤔 Maybe some netlify issue?

**Comment by stepan662** [comment]
It was already fixed here https://github.com/tolgee/documentation/pull/651/files
