### ISSUE TITLE
Removing that Horizontal Scrollbar.

### ISSUE THREAD

**Issue by sanketshinde3001** [tolgee/documentation#701]
**Describe the bug**
Horizontal Scrollbar is showing in Pricing Section.

**To Reproduce**
1. Go to 'https://tolgee.io/pricing'
2. See that scrollbar

**Expected behavior**
This page should fit in the laptop window perfectly without any scrollbar.

**Screenshots**
![image](https://github.com/user-attachments/assets/83bcaa19-8aa8-4180-b667-2ae317fe88c7)

**Versions and environment**
- Environment: Windows
- Browser: Brave

**Comment by sanketshinde3001** [comment]
@cyyynthia As issue is raised by me. I was waiting for assigning it to me. My code i already ready. Can you assign it ?

**Comment by moli-debugger** [comment]
@cyyynthia  

May i know that how it is gonna works now....

**Comment by cyyynthia** [comment]
Hey! I just did some quick triage work, the PR needs to be reviewed still (poke @stepan662)
